name: Release

on:
  #schedule:
  #  - cron:  '0 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      device-id:
        description: |
          Device ID, e.g. 'oriole'. See https://grapheneos.org/releases
        required: false
      ota-version:
        description: |
          OTA version, e.g. '2023121200', see https://grapheneos.org/releases
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Allow for switching to github-pages branch
          fetch-depth: 0 
      - run: sudo apt-get install -y jq curl git
      - name: release
        env:
          PASSPHRASE_AVB: ${{ secrets.PASSPHRASE_AVB }}
          PASSPHRASE_OTA: ${{ secrets.PASSPHRASE_OTA }}
          KEY_AVB_BASE64: ${{ secrets.KEY_AVB_BASE64 }}
          CERT_OTA_BASE64: ${{ secrets.CERT_OTA_BASE64 }}
          KEY_OTA_BASE64: ${{ secrets.KEY_OTA_BASE64 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          DEVICE_ID: ${{ github.event.inputs.device-id || 'oriole' }}
          OTA_VERSION: ${{ github.event.inputs.ota-version || 'latest' }}
        run: DEBUG=1 MAGISK_PREINIT_DEVICE='metadata' bash -c '. rooted-ota.sh && createAndReleaseRootedOta'

